name: 1workflow
on: [push]

jobs:
    run-shell-commands: 
        runs-on: ubuntu-latest
        steps: 
            - name: echo
              run: echo "Hello Testing the Workflow"
            - name: multiline
              run:  |
                node -v
                npm -v
    parallen-jobs:
        runs-on: macos-latest
        steps:
            - name: testingmac
              run: sw_vers
    dependant-job: 
        runs-on: windows-latest
        needs: run-shell-commands
        steps:
            - name: echo a string
              run: Write-output "testing Windows" 
            - name: Error Step
              run: doesnotexist 

