name: 2workflow
on: [push]


jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: setting an error message
              run: echo "::error::" Missing semicolon
            - name: Setting an error message with param
              run: echo "::error title=:Error:title file=index.html,line=2 endline=3 endColumn=7::Missing Semicolon"  