name: 4.1workflow action testing
on: [push]

jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: List the files Before
              run: ls -a
            - uses: actions/checkout@v3
            - name: List the files
              run: ls -a    