name: 8workflow-RUN
on: 
    workflow_run:
        workflows: [6workflow Repository Events]
        types: [completed]
jobs: 
    echo-string:
        runs-on: ubuntu-latest
        steps: 
            - run: echo "I was triggered becase "6workflow Repository Events" was Completed"        